/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ed;

import javax.swing.JOptionPane;

/**
 *
 * @author xentinel
 */
public class guiNueva extends javax.swing.JFrame {
    Parser parser = new Parser();
    TablasResuelve tablas = new TablasResuelve();
    ObtieneFNP fnp = new ObtieneFNP();
    
    String entrada = "";
    String salida = null;
    String conectivo = "";
    String formula = "";
    String[] expresiones = null;
    
    public static String tablaRes, tablaAtom, tablaTipo = "";
    public static String fnCP, fnDP, fnAtom = "";
    
    private static String ayuda0 = "- Aquí puedes escribir una o más proposiciones para ser evaluadas.\n"
            + "- Es indistinto el uso de mayúsculas o minúsculas.\n"
            + "- Puedes usar un punto para separar una proposición de otra, ";
    /*
            + "también se pueden usar comas para hacer agrupaciones.\n"
            + "- Si tu proposición incluye una conclusión, la puedes especificar usando la frase 'Por lo tanto, ...'\n\n"
            + "Ejemplo: Si Guillermo gana o Héctor gana, entonces Jorge pierde y Carlos pierde. Guillermo gana. Por lo tanto, Jorge pierde.\n\n";
    */
    private static String ayuda1 = "- Las atómicas se deben escribir sólo con mayúsculas.\n"
            + "- Los operadores admitidos son los siguientes:\n"
            + "        Negación [ 7 ]\n"
            + "        Conjunción [ ^ ]\n"
            + "        Disyunción [ v ]\n"
            + "        Condicional [ -> ]\n"
            + "        Bicondicional [ <-> ]\n"
            + "- También se permite el uso de paréntesis para hacer agrupaciones.\n\n"
            + "Ejemplo: (7Pv(Q^R))->S\n\n";
    /**
     * Creates new form guiNueva
     */
    public guiNueva() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoSimbolicoEntrada = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        salidaSimbolico = new javax.swing.JTextArea();
        convertirNaturalSimbolico = new javax.swing.JButton();
        ayudaSimbolico = new javax.swing.JButton();
        aTablaVdd = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaEntrada = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaVerdad = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        atomicasTVerdad = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        tipoProposicion = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        listoPTablaVerdad = new javax.swing.JButton();
        ayudaTVerdad = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        entradaFNP = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        atomicasFNP = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        textFNCP = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        textFNDP = new javax.swing.JTextArea();
        listoFNP = new javax.swing.JButton();
        ayudaFNP = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Estructuras Discretas 2016-2");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("UNIVERSIDAD NACIONAL AUTONOMA DE MÉXICO");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("FACULTAD DE INGENIERÍA");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Estructuras Discretas");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Profesor: Ing. Zaldivar Zamorategui Orlando");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("2016-2      Grupo: 4");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Integrantes:");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("Mario Antonio Aguilar Roldan");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setText("Romero Pérez Julio César");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ed/static/escudos.jpg"))); // NOI18N

        jLabel20.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel20.setText("Erik Torres Díaz");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel6))
                    .addComponent(jLabel20))
                .addContainerGap(169, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane4.addTab("Información", jPanel1);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("Escribe una o más proposiciones, si son varios conjuntos de ellas separalas con un punto.");

        textoSimbolicoEntrada.setColumns(20);
        textoSimbolicoEntrada.setRows(5);
        jScrollPane1.setViewportView(textoSimbolicoEntrada);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setText("Resultado:");

        salidaSimbolico.setColumns(20);
        salidaSimbolico.setRows(5);
        jScrollPane2.setViewportView(salidaSimbolico);

        convertirNaturalSimbolico.setText("Listo!");
        convertirNaturalSimbolico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                convertirNaturalSimbolicoMousePressed(evt);
            }
        });
        convertirNaturalSimbolico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertirNaturalSimbolicoActionPerformed(evt);
            }
        });

        ayudaSimbolico.setText("Ayuda!");
        ayudaSimbolico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ayudaSimbolicoMousePressed(evt);
            }
        });
        ayudaSimbolico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayudaSimbolicoActionPerformed(evt);
            }
        });

        aTablaVdd.setText("Tabla de Verdad");
        aTablaVdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aTablaVddMouseClicked(evt);
            }
        });
        aTablaVdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aTablaVddActionPerformed(evt);
            }
        });
        aTablaVdd.setVisible(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel10)
                .addContainerGap(291, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(aTablaVdd)
                        .addGap(18, 18, 18)
                        .addComponent(ayudaSimbolico)
                        .addGap(18, 18, 18)
                        .addComponent(convertirNaturalSimbolico)))
                .addGap(34, 34, 34))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ayudaSimbolico)
                            .addComponent(convertirNaturalSimbolico)
                            .addComponent(aTablaVdd))
                        .addGap(23, 23, 23)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane4.addTab("Convertir Lenguaje Natural a Simbólico", jPanel2);

        tablaEntrada.setColumns(20);
        tablaEntrada.setRows(5);
        jScrollPane4.setViewportView(tablaEntrada);

        tablaVerdad.setColumns(20);
        tablaVerdad.setRows(5);
        jScrollPane3.setViewportView(tablaVerdad);

        atomicasTVerdad.setColumns(20);
        atomicasTVerdad.setRows(5);
        jScrollPane5.setViewportView(atomicasTVerdad);

        tipoProposicion.setColumns(20);
        tipoProposicion.setRows(5);
        jScrollPane6.setViewportView(tipoProposicion);

        jLabel12.setText("Tipo de proposición");

        jLabel13.setText("Atómicas");

        jLabel14.setText("Tabla de verdad");

        jLabel15.setText("Escribe una fórmula proposicional");

        listoPTablaVerdad.setText("Listo!");
        listoPTablaVerdad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listoPTablaVerdadMousePressed(evt);
            }
        });
        listoPTablaVerdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listoPTablaVerdadActionPerformed(evt);
            }
        });

        ayudaTVerdad.setText("Ayuda");
        ayudaTVerdad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ayudaTVerdadMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(0, 715, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel13))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ayudaTVerdad)
                .addGap(18, 18, 18)
                .addComponent(listoPTablaVerdad)
                .addGap(28, 28, 28))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(listoPTablaVerdad)
                            .addComponent(ayudaTVerdad))
                        .addGap(11, 11, 11)
                        .addComponent(jLabel13)
                        .addGap(20, 20, 20)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane4.addTab("Tabla de Verdad", jPanel3);

        entradaFNP.setColumns(20);
        entradaFNP.setRows(5);
        jScrollPane7.setViewportView(entradaFNP);

        jLabel16.setText("Escribe una fórmula proposicional");

        atomicasFNP.setColumns(20);
        atomicasFNP.setRows(5);
        jScrollPane8.setViewportView(atomicasFNP);

        jLabel18.setText("Atómicas");

        jLabel17.setText("Forma Normal Conjuntiva Principal (FNCP)");

        textFNCP.setColumns(20);
        textFNCP.setRows(5);
        jScrollPane9.setViewportView(textFNCP);

        jLabel19.setText("Forma Normal Disyuntiva Principal (FNDP)");

        textFNDP.setColumns(20);
        textFNDP.setRows(5);
        jScrollPane10.setViewportView(textFNDP);

        listoFNP.setText("Listo!");
        listoFNP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listoFNPMousePressed(evt);
            }
        });

        ayudaFNP.setText("Ayuda!");
        ayudaFNP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ayudaFNPMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7)
                    .addComponent(jScrollPane8)
                    .addComponent(jScrollPane9)
                    .addComponent(jScrollPane10)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17)
                            .addComponent(jLabel19))
                        .addGap(0, 664, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ayudaFNP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listoFNP)
                        .addGap(12, 12, 12)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listoFNP)
                    .addComponent(ayudaFNP))
                .addGap(20, 20, 20)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        jTabbedPane4.addTab("Formas Normales Principales", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ayudaSimbolicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayudaSimbolicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ayudaSimbolicoActionPerformed

    private void listoPTablaVerdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listoPTablaVerdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listoPTablaVerdadActionPerformed

    private void convertirNaturalSimbolicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertirNaturalSimbolicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_convertirNaturalSimbolicoActionPerformed

    private void convertirNaturalSimbolicoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_convertirNaturalSimbolicoMousePressed
        // TODO add your handling code here:
        entrada = textoSimbolicoEntrada.getText();
        salida = parser.parse(entrada);
        salidaSimbolico.setText(salida);
        System.out.println(salida);
        aTablaVdd.setVisible(true);
    }//GEN-LAST:event_convertirNaturalSimbolicoMousePressed

    private void ayudaSimbolicoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ayudaSimbolicoMousePressed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,ayuda0);
    }//GEN-LAST:event_ayudaSimbolicoMousePressed

    private void ayudaTVerdadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ayudaTVerdadMousePressed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(null,ayuda1);
    }//GEN-LAST:event_ayudaTVerdadMousePressed

    private void ayudaFNPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ayudaFNPMousePressed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(null,ayuda1);
    }//GEN-LAST:event_ayudaFNPMousePressed

    private void listoPTablaVerdadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listoPTablaVerdadMousePressed
        // TODO add your handling code here:
        tablas.formu = tablaEntrada.getText();
        tablas.run();
        tablaVerdad.setText(tablaRes);
        atomicasTVerdad.setText(tablaAtom);
        tipoProposicion.setText(tablaTipo);
    }//GEN-LAST:event_listoPTablaVerdadMousePressed

    private void listoFNPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listoFNPMousePressed
        // TODO add your handling code here:
        fnp.form = entradaFNP.getText();
        fnp.run();
        atomicasFNP.setText(fnAtom);
        textFNCP.setText(fnCP);
        textFNDP.setText(fnDP);
    }//GEN-LAST:event_listoFNPMousePressed

    private void aTablaVddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aTablaVddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aTablaVddActionPerformed

    private void aTablaVddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aTablaVddMouseClicked
        // TODO add your handling code here:
        String cadenaParaTablas = parser.romperCadena(salida);
        tablaEntrada.setText(cadenaParaTablas);
        tablas.formu = cadenaParaTablas;
        tablas.run();
        tablaVerdad.setText(tablaRes);
        atomicasTVerdad.setText(tablaAtom);
        tipoProposicion.setText(tablaTipo);
    }//GEN-LAST:event_aTablaVddMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(guiNueva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(guiNueva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(guiNueva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(guiNueva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new guiNueva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aTablaVdd;
    private javax.swing.JTextArea atomicasFNP;
    private javax.swing.JTextArea atomicasTVerdad;
    private javax.swing.JButton ayudaFNP;
    private javax.swing.JButton ayudaSimbolico;
    private javax.swing.JButton ayudaTVerdad;
    private javax.swing.JButton convertirNaturalSimbolico;
    private javax.swing.JTextArea entradaFNP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JButton listoFNP;
    private javax.swing.JButton listoPTablaVerdad;
    private javax.swing.JTextArea salidaSimbolico;
    private javax.swing.JTextArea tablaEntrada;
    private javax.swing.JTextArea tablaVerdad;
    private javax.swing.JTextArea textFNCP;
    private javax.swing.JTextArea textFNDP;
    private javax.swing.JTextArea textoSimbolicoEntrada;
    private javax.swing.JTextArea tipoProposicion;
    // End of variables declaration//GEN-END:variables
}
